name: wp
services:
  mariadb:
    image: mariadb:11.3
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=${DB_NAME:-wordpress}
      - MYSQL_USER=${DB_USER:-wordpress} # DB user
      - MYSQL_PASSWORD=${DB_PASSWORD:-wordpress} # DB password
  wordpress:
    image: wordpress:fpm
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${DB_USER:-wordpress} # DB user
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD:-wordpress} # DB password
      - WORDPRESS_DB_NAME=${DB_NAME:-wordpress}
    volumes:
      - wordpress_data:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wp:ro
      - ./nginx/:/etc/nginx/templates:ro
      - ./ssl:/etc/ssl:ro
      - nginx_log:/var/log/nginx
    environment:
      - NGINX_HOST=${NGINX_HOST:-wp.lndo.site} # Your domain here.
volumes:
  mariadb_data:
  wordpress_data:
  nginx_log:
